"use strict";
const $=id=>document.getElementById(id),num=id=>Math.max(0,Number($(id).value)||0),money=v=>`$${v.toFixed(2)}`;
let activeRoute=null;
const show=route=>{if(activeRoute)sessionStorage.setItem(`scrappro.scroll.${activeRoute}`,String(scrollY));document.querySelectorAll(".screen").forEach(s=>s.classList.toggle("active",s.dataset.screen===route));document.querySelectorAll("[data-tab]").forEach(b=>b.classList.toggle("selected",b.dataset.tab===route));activeRoute=route;sessionStorage.setItem("scrappro.tab",route);requestAnimationFrame(()=>scrollTo(0,Number(sessionStorage.getItem(`scrappro.scroll.${route}`))||0))};
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>show(b.dataset.tab));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>show(b.dataset.go));
function profit(){const weight=num("p-weight"),price=num("p-price"),yieldRate=Math.min(100,num("p-yield"))/100,clean=$("p-clean").checked,multiplier=clean?1:.7,gross=weight*price*yieldRate*multiplier,expenses=num("p-fuel")+num("p-other")+num("p-hours")*num("p-rate"),potential=weight*price;$("p-net").value=money(gross-expenses);$("p-detail").textContent=`Gross ${money(gross)} · Expenses ${money(expenses)} · Yield/dirty loss ${money(Math.max(0,potential-gross))}`}
$("p-metal").onchange=e=>{$("p-price").value=e.target.value;profit()};["p-weight","p-price","p-yield","p-clean","p-fuel","p-other","p-hours","p-rate"].forEach(id=>$(id).addEventListener("input",profit));
function wire(){const weight=num("w-weight"),yieldRate=Math.min(100,num("w-yield"))/100,insulated=weight*num("w-insulated"),stripped=weight*yieldRate*num("w-bare"),gain=stripped-insulated,speed=num("w-speed"),hours=speed>0?weight/speed:0,wage=hours>0?gain/hours:0,machine=num("w-machine"),payback=machine>0&&gain>0?machine/gain:null;$("w-rec").textContent=wage>=25?"STRIP IT":"SELL INSULATED";$("w-gain").value=money(gain);$("w-detail").textContent=`${hours.toFixed(2)} labor hr · ${money(wage)}/hr · ${payback?payback.toFixed(1)+" similar loads to repay machine":"No finite machine payback"}`}
$("w-type").onchange=e=>{$("w-yield").value=e.target.selectedOptions[0].dataset.yield;wire()};["w-weight","w-yield","w-insulated","w-bare","w-speed","w-machine"].forEach(id=>$(id).addEventListener("input",wire));
function paintMeter(id,statusId,pct){const bar=$(id),status=$(statusId),level=pct<80?"green":pct<100?"yellow":"red";bar.style.width=`${Math.min(100,pct)}%`;bar.className=`status-${level}`;bar.style.background=`var(--${level})`;status.className=`status-${level}`;status.textContent=`${pct.toFixed(1)}% used`}
function payload(){const truckMax=num("v-max"),truckPct=truckMax>0?num("v-cargo")/truckMax*100:0,trailerCap=Math.max(0,num("t-gvwr")-num("t-empty")),trailerPct=trailerCap>0?num("t-cargo")/trailerCap*100:0,loaded=num("t-empty")+num("t-cargo"),tonguePct=loaded>0?num("t-tongue")/loaded*100:0;paintMeter("truck-meter","truck-status",truckPct);paintMeter("trailer-meter","trailer-status",trailerPct);const level=tonguePct>=10&&tonguePct<=15?"green":tonguePct>=8&&tonguePct<=17?"yellow":"red";$("tongue-result").className=`result status-${level}`;$("tongue-status").value=`${tonguePct.toFixed(1)}%`;$("tongue-detail").textContent=`Safe measured range: ${(loaded*.10).toFixed(0)}–${(loaded*.15).toFixed(0)} lb · place about 60% of cargo ahead of the axles`}
["v-max","v-cargo","t-gvwr","t-empty","t-cargo","t-tongue"].forEach(id=>$(id).addEventListener("input",payload));
const wizardSteps={magnet:{q:"Does a strong magnet stick?",o:[["Yes — ferrous",()=>wizard("spark")],["No — non-ferrous",()=>wizard("color")]]},spark:{q:"Spark test result? Use eye/face protection.",o:[["Long bright branching sparks",()=>result("Carbon steel / high-carbon iron","Low-value ferrous")],["Short dull red sparks",()=>result("Cast or wrought iron","Low-value ferrous")]]},color:{q:"Color beneath paint or oxidation?",o:[["Red / orange",()=>result("Copper — inspect for Bare Bright, #1 or #2","High-value target")],["Yellow",()=>result("Brass","High-value target")],["Silver / gray",()=>wizard("acid")]]},acid:{q:"Commercial test kit indicates zinc/galvanized reaction? Use PPE; never mix acids.",o:[["Yes",()=>result("Zinc / galvanized alloy","Verify with yard")],["No / not tested",()=>wizard("weight")]]},weight:{q:"How heavy is it for its size?",o:[["Heavy / dense",()=>result("Lead or non-magnetic stainless","Verify safely")],["Light",()=>result("Cast or sheet aluminum","Non-ferrous")]]}};
function wizard(step){const s=wizardSteps[step];$("wizard").innerHTML=`<b>${s.q}</b><div class="wizard-options"></div>`;const box=$("wizard").querySelector("div");s.o.forEach(([label,fn])=>{const b=document.createElement("button");b.textContent=label;b.onclick=fn;box.appendChild(b)})}function result(name,kind){$("wizard").innerHTML=`<small>IDENTIFIED TARGET</small><h2>${name}</h2><p>${kind}</p><button id="restart">START OVER</button>`;$("restart").onclick=()=>wizard("magnet")}
const yards=[{name:"Apex Metals Recycling",miles:2.4,hours:"8:00 AM–4:30 PM",phone:"5550101",lat:40.7128,lng:-74.006,types:["ferrous","nonferrous"]},{name:"Steel City Scrap",miles:4.8,hours:"7:30 AM–5:00 PM",phone:"5550202",lat:40.73,lng:-74.015,types:["ferrous","nonferrous","vehicles"]},{name:"Quick Cash Non-Ferrous",miles:6.1,hours:"9:00 AM–3:00 PM",phone:"5550303",lat:40.705,lng:-73.995,types:["nonferrous"]}];
function renderYards(){const filter=$("yard-filter").value,list=$("yard-list");list.innerHTML="";yards.filter(y=>filter==="all"||y.types.includes(filter)).forEach(y=>{const card=document.createElement("article");card.className="card";card.innerHTML=`<div class="split"><b>${y.name}</b><strong>${y.miles.toFixed(1)} mi</strong></div><p>Open today: ${y.hours}</p><small>Accepts: ${y.types.join(" · ")}</small><div class="yard-actions"><a href="tel:${y.phone}"><button>CALL</button></a><a href="https://www.google.com/maps/search/?api=1&query=${y.lat},${y.lng}" target="_blank" rel="noopener"><button class="primary">NAVIGATE NOW</button></a></div>`;list.appendChild(card)})}$("yard-filter").onchange=renderYards;
profit();wire();payload();wizard("magnet");renderYards();show(sessionStorage.getItem("scrappro.tab")||"home");
